### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by auscompgeek** [sbhs-forkbombers/sbhs-timetable#6]
'nuff said

**Comment by gnustomp** [comment]
;_;

**Comment by auscompgeek** [comment]
inb4 ported to perl

**Comment by fourkbomb** [comment]
inb4 ported to FORTRAN

<sup>java is coming</sup>

**Comment by gnustomp** [comment]
inb4 ported to x86, complete with TCP/IP stack, HTTP and HTCPCP servers,
SSL/TLS stack and DB. Runs as an operating system.

@keepcalm444 that java footnote was sneaky. Didn't land in the email preview.

**Comment by fourkbomb** [comment]
hmm. @gnustomp what if I want to run on my pi? might need portability. perhaps we should write something that compiles human-readable code directly to machine code.

**Comment by gnustomp** [comment]
Write an abstraction layer for each platform you want to port, and then compile x86 into that. Totally not over-complicated.

**Comment by fourkbomb** [comment]
I think we should write a compiler that compiles code to a semi-compiled form, and then have an interpreter that would interpret this semi-compiled code into actual code.

<sup>[Here's one I wrote earlier](http://openjdk.java.net)</sup>

**Comment by auscompgeek** [comment]
Clearly Pascal is the only true cross-platform language.

**Comment by fourkbomb** [comment]
Is Pascal for iOS a thing? HP-UX? OS/2? VMS? AmigaOS? MINIX? System V?

**Comment by auscompgeek** [comment]
Yes to all the above (from memory).

**Comment by fourkbomb** [comment]
http://www.cpan.org/ports/archive-2011-03-26.html

anyway, Pascal for PalmOS? zOS? Xbox One? Hurd? Blackberry? Symbian OS?

**Comment by auscompgeek** [comment]
Xbox One? Probably not, that thing is so closed, it's not even funny.

zOS? Never heard of it.

Probably yes to the rest of them though.

**Comment by gnustomp** [comment]
Apparently email replies aren't parsed as markdown.
So...
Xbox One is based on Windows, so yes. ~~Unless architecture shiftiness.~~ It's x86-64

**Comment by fourkbomb** [comment]
see [sbhs-timetable-node](https://github.com/sbhs-forkbombers/sbhs-timetable-node)

**Comment by gnustomp** [comment]
...

**Comment by auscompgeek** [comment]
hey, I didn't want this cluttering up my issues dashboard
