### ISSUE TITLE
Um.

### ISSUE THREAD

**Issue by eddieqiii** [sbhs-forkbombers/sbhs-timetable#7]
![lel](https://cloud.githubusercontent.com/assets/7733667/3116043/ed2970d0-e712-11e3-8cd0-512cecaab1b5.PNG)

(I didn't change it, apparently you can input any text that includes "staff" in the Change Year thing. Changed my ID for anonymity.)

**Comment by gnustomp** [comment]
Are you Ram?
But anyway this won't exist for much longer, refer to https://github.com/sbhs-forkbombers/sbhs-timetable-node

**Comment by eddieqiii** [comment]
1. I am a person that has no understanding of Git. I am not Ram.
2. kcoolclosed
